# PyTorch

## Create a Tensor

### Empty values

In [1]:
import torch

In [2]:
a = torch.empty(1)
a

tensor([2.2073e-07])

In [3]:
b = torch.empty(2)
b

tensor([-2.2027e+07,  3.2041e-41])

In [4]:
b.size()

torch.Size([2])

In [5]:
c = torch.empty(3,4)
c

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.5835e-42, 4.3262e-41, 2.8026e-45, 0.0000e+00],
        [2.8026e-45, 1.4013e-45, 1.6381e-42, 3.2041e-41]])

In [6]:
c.ndimension()

2

In [7]:
d = torch.empty(3,4,5)
d

tensor([[[-3.4313e+05,  3.2041e-41,  3.2230e-44,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,         nan,         nan,  0.0000e+00,  0.0000e+00],
         [ 2.4803e-43,  0.0000e+00, -8.6897e+08,  3.2041e-41, -3.8009e-23],
         [ 4.3262e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,         nan],
         [        nan,  0.0000e+00,  0.0000e+00,  1.4013e-45,  5.6052e-45],
         [ 1.3593e-43,  0.0000e+00, -8.6895e+08,  3.2041e-41, -8.6872e+08],
         [ 3.2041e-41, -3.4314e+05,  3.2041e-41,         nan,         nan]],

        [[ 5.3249e-44,  0.0000e+00,         nan,         nan,  0.0000e+00],
         [ 0.0000e+00,  4.6243e-44,  0.0000e+00, -8.6744e+08,  3.2041e-41],
         [-8.6899e+08,  3.2041e-41,  3.5873e-43,  0.0000e+00,  1.5695e-43],
         [ 0.0000e+00,  5.9665e+16,  3.2045e-41,  3.6434e-44,  0.0000e+00]]])

In [8]:
d.dtype

torch.float32

In [9]:
type(d)

torch.Tensor

### One or Zero Values

In [10]:
a = torch.ones(3,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
b = torch.zeros(3,4)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Random Values

In [12]:
a = torch.rand(1,2)
a

tensor([[0.3677, 0.8936]])

In [13]:
a.shape

torch.Size([1, 2])

In [14]:
a.size()

torch.Size([1, 2])

In [15]:
a = torch.rand(3,4,5)
a

tensor([[[0.0149, 0.1924, 0.2133, 0.4993, 0.1849],
         [0.0084, 0.4762, 0.3673, 0.4520, 0.6035],
         [0.8880, 0.9597, 0.4498, 0.6484, 0.0389],
         [0.2170, 0.8621, 0.7875, 0.3017, 0.7760]],

        [[0.9711, 0.2208, 0.9318, 0.2243, 0.2233],
         [0.4029, 0.9636, 0.5784, 0.8200, 0.0890],
         [0.5394, 0.0246, 0.7598, 0.8384, 0.7287],
         [0.1083, 0.5175, 0.0162, 0.4107, 0.3734]],

        [[0.6854, 0.7272, 0.5330, 0.4623, 0.3766],
         [0.3667, 0.1564, 0.1288, 0.6750, 0.4934],
         [0.6233, 0.9199, 0.7736, 0.6313, 0.1996],
         [0.0401, 0.0941, 0.0763, 0.4678, 0.1576]]])

### Tensor Values

In [16]:
a = torch.tensor([1,2,3,4])
a

tensor([1, 2, 3, 4])

In [17]:
a.dtype

torch.int64

In [18]:
a = torch.tensor([[2,4,6,8], [1,3,5,7],[1,2,3,4]])
a

tensor([[2, 4, 6, 8],
        [1, 3, 5, 7],
        [1, 2, 3, 4]])

In [19]:
a.dtype

torch.int64

In [20]:
a = torch.tensor([[[2,4,6,8], [1,3,5,7],[1,2,3,4]],[[2,4,6,8], [1,3,5,7],[1,2,3,4]]] )
a

tensor([[[2, 4, 6, 8],
         [1, 3, 5, 7],
         [1, 2, 3, 4]],

        [[2, 4, 6, 8],
         [1, 3, 5, 7],
         [1, 2, 3, 4]]])

In [21]:
a.dtype

torch.int64

In [22]:
a = torch.ones(1, dtype=torch.float16)
a

tensor([1.], dtype=torch.float16)

In [23]:
a.shape

torch.Size([1])

In [24]:
a = torch.ones(1, dtype=torch.double)
a

tensor([1.], dtype=torch.float64)

In [25]:
a = torch.ones(1, dtype=torch.int16)
a

tensor([1], dtype=torch.int16)

In [26]:
a.dtype

torch.int16