# Reshape a Tensor

In [1]:
import torch

In [2]:
a = torch.rand(3,4)
a

tensor([[0.2167, 0.8125, 0.9073, 0.4368],
        [0.5211, 0.7710, 0.2529, 0.5899],
        [0.6141, 0.6120, 0.1640, 0.3368]])

### View Function

In [3]:
a = a.view(6,2)
a

tensor([[0.2167, 0.8125],
        [0.9073, 0.4368],
        [0.5211, 0.7710],
        [0.2529, 0.5899],
        [0.6141, 0.6120],
        [0.1640, 0.3368]])

### Reshape Function

In [4]:
a = a.reshape(4,3)
a

tensor([[0.2167, 0.8125, 0.9073],
        [0.4368, 0.5211, 0.7710],
        [0.2529, 0.5899, 0.6141],
        [0.6120, 0.1640, 0.3368]])

In [5]:
a = a.view(1,12)
a

tensor([[0.2167, 0.8125, 0.9073, 0.4368, 0.5211, 0.7710, 0.2529, 0.5899, 0.6141,
         0.6120, 0.1640, 0.3368]])

In [6]:
a = a.reshape(12,1)
a

tensor([[0.2167],
        [0.8125],
        [0.9073],
        [0.4368],
        [0.5211],
        [0.7710],
        [0.2529],
        [0.5899],
        [0.6141],
        [0.6120],
        [0.1640],
        [0.3368]])

# Convert a Tensor into Numpy

In [7]:
a = torch.rand(3,4)
a

tensor([[0.2800, 0.0801, 0.5185, 0.5949],
        [0.8694, 0.7868, 0.5781, 0.7943],
        [0.0810, 0.2807, 0.6828, 0.2804]])

In [8]:
a.dtype

torch.float32

In [9]:
type(a)

torch.Tensor

In [10]:
b = a.numpy()

In [11]:
type(b)

numpy.ndarray

In [12]:
b.dtype

dtype('float32')

In [13]:
b[0][0] = 1.0
b

array([[1.        , 0.08014941, 0.5185101 , 0.5949259 ],
       [0.86936736, 0.7867927 , 0.5780677 , 0.7943472 ],
       [0.08097219, 0.28068256, 0.68278337, 0.28042483]], dtype=float32)

In [14]:
# 1 also show in tensor, because both numpy and tensor in cpu, so they shared memory

In [15]:
a

tensor([[1.0000, 0.0801, 0.5185, 0.5949],
        [0.8694, 0.7868, 0.5781, 0.7943],
        [0.0810, 0.2807, 0.6828, 0.2804]])

In [16]:
a.device


device(type='cpu')

# Convert Numpy to Tensor

In [17]:
import numpy as np

In [18]:
num_a = np.array([1,2,3])


In [19]:
type(num_a)

numpy.ndarray

In [20]:
num_a.dtype

dtype('int64')

### as_tensor Function

In [21]:
a = torch.as_tensor(num_a.astype(np.float16))
a

tensor([1., 2., 3.], dtype=torch.float16)

In [22]:
type(a)

torch.Tensor

In [23]:
a.dtype

torch.float16

### from_numpy Function

In [24]:
num_a = np.array([1,2,4])
num_a

array([1, 2, 4])

In [25]:
num_a.dtype

dtype('int64')

In [26]:
type(num_a)

numpy.ndarray

In [27]:
b = torch.from_numpy(num_a.astype(np.float32))
b

tensor([1., 2., 4.])

In [28]:
type(b)

torch.Tensor

# Slicing

In [29]:
a = torch.rand(4,5)
a

tensor([[0.8044, 0.4569, 0.5947, 0.1520, 0.6576],
        [0.7376, 0.2733, 0.0137, 0.6143, 0.3801],
        [0.0064, 0.5012, 0.9317, 0.5999, 0.3564],
        [0.9504, 0.5831, 0.1151, 0.6523, 0.5901]])

In [30]:
a[:,1:]

tensor([[0.4569, 0.5947, 0.1520, 0.6576],
        [0.2733, 0.0137, 0.6143, 0.3801],
        [0.5012, 0.9317, 0.5999, 0.3564],
        [0.5831, 0.1151, 0.6523, 0.5901]])

In [31]:
a[1:3,0:2]

tensor([[0.7376, 0.2733],
        [0.0064, 0.5012]])

# Stack and Concatenate

In [32]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3689, 0.9684, 0.3238],
        [0.2108, 0.9799, 0.7286]])
tensor([[0.1211, 0.8507, 0.3526],
        [0.1522, 0.9623, 0.1661]])


In [33]:
a.shape

torch.Size([2, 3])

In [34]:
b.shape

torch.Size([2, 3])

### Stack Function

In [35]:
c = torch.stack([a,b], axis=0)
c

tensor([[[0.3689, 0.9684, 0.3238],
         [0.2108, 0.9799, 0.7286]],

        [[0.1211, 0.8507, 0.3526],
         [0.1522, 0.9623, 0.1661]]])

In [36]:
c.shape

torch.Size([2, 2, 3])

### Concatenate Function

In [37]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a.shape)
print(b.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [38]:
c = torch.cat([a,b], axis= 0)

In [39]:
c

tensor([[0.2921, 0.5934, 0.3736],
        [0.4350, 0.5481, 0.3364],
        [0.0247, 0.8090, 0.9651],
        [0.0969, 0.2472, 0.8487]])

In [40]:
c.shape

torch.Size([4, 3])

In [41]:
d = torch.rand(5,3)
d

tensor([[0.2790, 0.8138, 0.2501],
        [0.8119, 0.9848, 0.7671],
        [0.7069, 0.3932, 0.7897],
        [0.5444, 0.9308, 0.0786],
        [0.5876, 0.1108, 0.5953]])

In [42]:
e = torch.cat([a,d], axis=0)
e

tensor([[0.2921, 0.5934, 0.3736],
        [0.4350, 0.5481, 0.3364],
        [0.2790, 0.8138, 0.2501],
        [0.8119, 0.9848, 0.7671],
        [0.7069, 0.3932, 0.7897],
        [0.5444, 0.9308, 0.0786],
        [0.5876, 0.1108, 0.5953]])

In [43]:
e.shape

torch.Size([7, 3])

# Copy of a Tensor


* **Shallow Memory** : Shared Memory

* **Deep Memory**: Independent - Not Shared Momery

### Shallow Memory

In [44]:
num1 = torch.rand(2,4)
num1

tensor([[0.5794, 0.8605, 0.7746, 0.6381],
        [0.4836, 0.0159, 0.2072, 0.0594]])

In [45]:
num2 = num1

In [46]:
num2

tensor([[0.5794, 0.8605, 0.7746, 0.6381],
        [0.4836, 0.0159, 0.2072, 0.0594]])

In [47]:
num2[0][0] = 2.0

In [48]:
num2

tensor([[2.0000, 0.8605, 0.7746, 0.6381],
        [0.4836, 0.0159, 0.2072, 0.0594]])

In [49]:
num1

tensor([[2.0000, 0.8605, 0.7746, 0.6381],
        [0.4836, 0.0159, 0.2072, 0.0594]])

### Clone Function - Deep Memory

In [50]:
num3 = num1.clone()

In [51]:
num3

tensor([[2.0000, 0.8605, 0.7746, 0.6381],
        [0.4836, 0.0159, 0.2072, 0.0594]])

In [52]:
num3[0][0] = 1.
num3

tensor([[1.0000, 0.8605, 0.7746, 0.6381],
        [0.4836, 0.0159, 0.2072, 0.0594]])

In [53]:
num1

tensor([[2.0000, 0.8605, 0.7746, 0.6381],
        [0.4836, 0.0159, 0.2072, 0.0594]])