# Basic Maths Operations


In [2]:
import torch

In [3]:
a = torch.ones(2,3)

In [4]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
b = torch.ones(2,3)

In [6]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## Add

In [7]:
c = torch.add(a,b)

In [8]:
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [9]:
a.add_(b)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [10]:
a

tensor([[2., 2., 2.],
        [2., 2., 2.]])

## Subtract

In [11]:
c = torch.sub(a,b)

In [12]:
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## Multiply

In [13]:
c = torch.mul(a,b)

In [14]:
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

## Division

In [15]:
c = torch.div(a,b)

In [16]:
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

## Transpose

In [17]:
a.T

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])